import type { BotProfile } from "./types";

const ashPkg = ["Ash Blossom & Joyous Spring", "Infinite Impermanence", "Effect Veiler", 'Maxx "C"', "Called by the Grave", "Crossout Designator", "Forbidden Droplet", "Nibiru, the Primal Being", "Droll & Lock Bird", "Ghost Belle & Haunted Mansion", "Mulcharmy Fuwalos"];

function p(partial: Omit<BotProfile, "breakers" | "extraAggression" | "acceptTriggers" | "minAttackers" | "responders"> & Partial<Pick<BotProfile, "breakers" | "extraAggression" | "acceptTriggers" | "minAttackers" | "responders">>): BotProfile {
  return {
    ...partial,
    responders: [...new Set([...(partial.responders ?? []), ...ashPkg])],
    breakers: partial.breakers?.length ? partial.breakers : ["Forbidden Droplet", "Raigeki", "Lightning Storm"],
    extraAggression: partial.extraAggression ?? 0.75,
    acceptTriggers: partial.acceptTriggers ?? true,
    minAttackers: partial.minAttackers ?? 1,
  };
}

const PROFILES: BotProfile[] = [
  p({
    premadeId: "tcg-kewl-tune",
    name: "Kewl Tune",
    role: "combo",
    playstyle: "Synchro flood. NS Cue/Rotary, climb tuners into Remix/B2B/Track Maker, end on omni-adjacent Synchros + S:P.",
    comboOutline: [
      "Normal Summon Cue or Rotary (or Mix/Reco as extender).",
      "Use tuner effects to Special more Kewl Tune names.",
      "Synchro into Track Maker / RS / Remix / B2B.",
      "Climb to Crystal Wing / Chaos Angel / TY-PHON.",
      "Leave S:P + I:P as follow-up.",
    ],
    endBoard: ["Kewl Tune Remix", "Kewl Tune B2B", "Crystal Wing Synchro Dragon", "S:P Little Knight"],
    normalSummon: ["Kewl Tune Cue", "Kewl Tune Rotary", "Kewl Tune Mix", "Kewl Tune Reco", "Kewl Tune Clip"],
    engineSpells: ["Kewl Tune Synchro", 'JJ "Kewl Tune"', "Synchro Overtake", "Duelist Genesis"],
    setBackrow: ["Infinite Impermanence", "Kewl Tune Playlist"],
    extraBosses: ["Kewl Tune Remix", "Kewl Tune Track Maker", "Kewl Tune RS", "Kewl Tune B2B", "Kewl Tune Crackle", "Crystal Wing Synchro Dragon", "Chaos Angel", "S:P Little Knight", "I:P Masquerena", "Super Starslayer TY-PHON - Sky Crisis"],
    responders: [],
    extraAggression: 0.9,
  }),
  p({
    premadeId: "md-kewl-tune",
    name: "Kewl Tune",
    role: "combo",
    playstyle: "Same Synchro climb as TCG with Maxx C in the response package.",
    comboOutline: ["NS Cue/Rotary", "Climb Kewl Tune Synchros", "Hold Maxx C / Ash for opponent combo"],
    endBoard: ["Kewl Tune Remix", "Baronne de Fleur", "S:P Little Knight"],
    normalSummon: ["Kewl Tune Cue", "Kewl Tune Rotary", "Kewl Tune Mix", "Kewl Tune Reco", "Kewl Tune Clip"],
    engineSpells: ["Kewl Tune Synchro", 'JJ "Kewl Tune"', "Synchro Overtake", "Duelist Genesis"],
    setBackrow: ["Infinite Impermanence", "Kewl Tune Playlist"],
    extraBosses: ["Kewl Tune Remix", "Kewl Tune Track Maker", "Kewl Tune RS", "Kewl Tune B2B", "Baronne de Fleur", "Chaos Angel", "Crystal Wing Synchro Dragon", "S:P Little Knight"],
    responders: [],
    extraAggression: 0.9,
  }),
  p({
    premadeId: "tcg-branded-dracotail",
    name: "Branded Dracotail",
    role: "midrange",
    playstyle: "Branded Fusion grind + compact Dracotail fuses. Search Aluber/Cartesia, fuse Albaz lines, recycle with Branded in Red.",
    comboOutline: ["Activate Branded Fusion / Opening", "Fuse Fallen of Albaz into Mirrorjade/Albion lines", "Use Dracotail names to fuse Arthalion/Gulamel", "Set Branded/Dracotail traps"],
    endBoard: ["Mirrorjade the Iceblade Dragon", "Albion the Branded Dragon", "Dracotail Arthalion"],
    normalSummon: ["Aluber the Jester of Despia", "Dracotail Lukias", "Fallen of Albaz", "Blazing Cartesia, the Virtuous"],
    engineSpells: ["Branded Fusion", "Branded Opening", "The Fallen & The Virtuous", "Branded in High Spirits", "Branded in Red", "Ketu Dracotail", "Rahu Dracotail", "Fusion Deployment", "Foolish Burial"],
    setBackrow: ["Branded Retribution", "Dracotail Flame", "Infinite Impermanence"],
    extraBosses: ["Mirrorjade the Iceblade Dragon", "Albion the Branded Dragon", "Lubellion the Searing Dragon", "Dracotail Arthalion", "Guardian Chimera", "Rindbrumm the Striking Dragon"],
    responders: [],
  }),
  p({
    premadeId: "md-branded",
    name: "Branded",
    role: "midrange",
    playstyle: "Classic Branded Fusion loop with Bystials. Prioritize Branded Fusion, climb Mirrorjade + Sanctifire.",
    comboOutline: ["Branded Fusion / Opening", "Albaz fusions", "Bystial backup", "Set Retribution"],
    endBoard: ["Mirrorjade the Iceblade Dragon", "Albion the Sanctifire Dragon", "Titaniklad the Ash Dragon"],
    normalSummon: ["Aluber the Jester of Despia", "Fallen of Albaz", "Blazing Cartesia, the Virtuous", "The Bystial Lubellion"],
    engineSpells: ["Branded Fusion", "Branded Opening", "Branded in High Spirits", "Branded in Red", "Fusion Deployment", "Gold Sarcophagus"],
    setBackrow: ["Branded Retribution", "Brightest, Blazing, Branded King", "Infinite Impermanence"],
    extraBosses: ["Mirrorjade the Iceblade Dragon", "Albion the Branded Dragon", "Albion the Sanctifire Dragon", "Lubellion the Searing Dragon", "Masquerade the Blazing Dragon"],
    responders: [],
  }),
  p({
    premadeId: "tcg-dracotail",
    name: "Dracotail",
    role: "midrange",
    playstyle: "Midrange fusion. Pair a Dracotail name with another monster, fuse on either turn, loop traps.",
    comboOutline: ["NS Lukias / Faimena", "Fuse using Ketu/Rahu/Poly", "Set Flame/Horn/Sting", "Faimena fuses on opponent turn if able"],
    endBoard: ["Dracotail Arthalion", "Dracotail Gulamel", "S:P Little Knight"],
    normalSummon: ["Dracotail Lukias", "Dracotail Faimena", "Dracotail Mululu", "Dracotail Urgula", "Dracotail Pan"],
    engineSpells: ["Ketu Dracotail", "Rahu Dracotail", "Polymerization", "Super Polymerization"],
    setBackrow: ["Dracotail Flame", "Dracotail Horn", "Dracotail Sting", "Infinite Impermanence"],
    extraBosses: ["Dracotail Arthalion", "Dracotail Gulamel", "Dracotail Shaulas", "Guardian Chimera", "S:P Little Knight"],
    responders: [],
  }),
  p({
    premadeId: "md-dracotail",
    name: "Dracotail",
    role: "midrange",
    playstyle: "MD Dracotail midrange with Maxx C package.",
    comboOutline: ["NS Dracotail name", "Fuse Arthalion line", "Set archetype traps"],
    endBoard: ["Dracotail Arthalion", "Dracotail Gulamel", "S:P Little Knight"],
    normalSummon: ["Dracotail Lukias", "Dracotail Faimena", "Dracotail Mululu", "Dracotail Urgula", "Dracotail Pan"],
    engineSpells: ["Ketu Dracotail", "Rahu Dracotail", "Polymerization", "Super Polymerization"],
    setBackrow: ["Dracotail Flame", "Dracotail Horn", "Dracotail Sting", "Infinite Impermanence"],
    extraBosses: ["Dracotail Arthalion", "Dracotail Gulamel", "Dracotail Shaulas", "Guardian Chimera", "S:P Little Knight"],
    responders: [],
  }),
  p({
    premadeId: "tcg-mitsurugi",
    name: "Mitsurugi",
    role: "combo",
    playstyle: "Ritual engine. Search Prayers/Ritual, tribute Mikoto names, land Murakumo/Habakiri disruption.",
    comboOutline: ["Activate Mitsurugi Prayers / Ritual", "NS a Mikoto", "Ritual Murakumo or Habakiri", "Link into Dyna Mondo / generics"],
    endBoard: ["Ame no Murakumo no Mitsurugi", "Ame no Habakiri no Mitsurugi", "S:P Little Knight"],
    normalSummon: ["Mitsurugi no Mikoto, Saji", "Mitsurugi no Mikoto, Kusanagi", "Mitsurugi no Mikoto, Aramasa", "Mitsurugi no Miko, Wousu"],
    engineSpells: ["Mitsurugi Prayers", "Mitsurugi Ritual", "Mitsurugi Magatama", "Mitsurugi Mirror", "Pre-Preparation of Rites", "Preparation of Rites"],
    setBackrow: ["Mitsurugi Great Purification", "Mitsurugi Tempest", "Infinite Impermanence"],
    extraBosses: ["Dyna Mondo", "S:P Little Knight", "I:P Masquerena", "Accesscode Talker", "Divine Arsenal AA-ZEUS - Sky Thunder"],
    responders: [],
    extraAggression: 0.55,
  }),
  p({
    premadeId: "md-mitsurugi",
    name: "Mitsurugi",
    role: "combo",
    playstyle: "MD Ritual Mitsurugi with generic Extra toolbox.",
    comboOutline: ["Prayers/Ritual", "Ritual boss", "Generic links/xyz"],
    endBoard: ["Ame no Murakumo no Mitsurugi", "S:P Little Knight"],
    normalSummon: ["Mitsurugi no Mikoto, Saji", "Mitsurugi no Mikoto, Kusanagi", "Mitsurugi no Mikoto, Aramasa", "Mitsurugi no Miko, Wousu"],
    engineSpells: ["Mitsurugi Prayers", "Mitsurugi Ritual", "Pre-Preparation of Rites", "Mitsurugi Magatama"],
    setBackrow: ["Mitsurugi Great Purification", "Infinite Impermanence"],
    extraBosses: ["Dyna Mondo", "S:P Little Knight", "Accesscode Talker", "Divine Arsenal AA-ZEUS - Sky Thunder"],
    responders: [],
    extraAggression: 0.55,
  }),
  p({
    premadeId: "tcg-doomz",
    name: "DoomZ",
    role: "combo",
    playstyle: "Machine/Power Patron climb. NS Drastea/Elara, overlay DoomZ Xyz, crash into ZEUS/TY-PHON.",
    comboOutline: ["NS DoomZ main deck machine", "Climb into Drastrius / Graflareio / Diactorus", "Generic rank 8/10 finishers"],
    endBoard: ["DoomZ XII End - Drastrius", "DoomZ XIII Over - Graflareio", "Divine Arsenal AA-ZEUS - Sky Thunder"],
    normalSummon: ["DoomZ XII Zero - Drastea", "DoomZ VII Seven - Elara", "DoomZ V Five - Amalthe", "Jupredo the Shademachine Power Patron"],
    engineSpells: ["DoomZ Raiders", "DoomZ Change", 'DoomZ Command "A.D.R.A.S.T.E.I.A."', 'DoomZ Command "D.O.O.M.D.U.R.G."', "Terraforming"],
    setBackrow: ["DoomZ Destruction", "Infinite Impermanence"],
    extraBosses: ["DoomZ XII End - Drastrius", "DoomZ XIII Over - Graflareio", "DoomZ Break - Diactorus", "Divine Arsenal AA-ZEUS - Sky Thunder", "S:P Little Knight"],
    responders: [],
  }),
  p({
    premadeId: "tcg-maliss",
    name: "Maliss",
    role: "combo",
    playstyle: "Banish-Link combo. NS White Rabbit/Dormouse/Chessy, banish names, climb Red Ransom → Hearts Crypter → Accesscode.",
    comboOutline: ["NS a Maliss <P> name", "Banish/recur via Underground", "Link White Binder / Red Ransom / Hearts Crypter", "Accesscode to close"],
    endBoard: ["Maliss <Q> Hearts Crypter", "Maliss <Q> Red Ransom", "Accesscode Talker"],
    normalSummon: ["Maliss <P> White Rabbit", "Maliss <P> Dormouse", "Maliss <P> Chessy Cat", "Maliss <P> March Hare"],
    engineSpells: ["Maliss in Underground", "Maliss in the Mirror", "Allure of Darkness", "Gold Sarcophagus", "Terraforming"],
    setBackrow: ["Maliss <C> GWC-06", "Maliss <C> MTP-07", "Maliss <C> TB-11", "Infinite Impermanence", "Dimensional Barrier"],
    extraBosses: ["Maliss <Q> Hearts Crypter", "Maliss <Q> Red Ransom", "Maliss <Q> White Binder", "Accesscode Talker", "Transcode Talker", "S:P Little Knight"],
    responders: [],
    extraAggression: 0.92,
  }),
  p({
    premadeId: "tcg-radiant-typhoon",
    name: "Radiant Typhoon",
    role: "midrange",
    playstyle: "Spell-heavy midrange. NS Krosea/Eldam/Swen, search MST-like spells, Link Varuroon.",
    comboOutline: ["NS Radiant Typhoon name", "Chant/Manifestation/Vision", "Link Marine Eidolon", "Flood with Rivalry/Gozen if ahead"],
    endBoard: ["Radiant Typhoon Varuroon, the Marine Eidolon", "Promethean Princess, Bestower of Flames", "S:P Little Knight"],
    normalSummon: ["Radiant Typhoon Krosea", "Radiant Typhoon Eldam", "Radiant Typhoon Swen", "Radiant Typhoon Meghala", "Radiant Typhoon Fonix, the Great Flame", "Radiant Typhoon Varuroon, the Vibrant Vortex"],
    engineSpells: ["Radiant Typhoon Chant", "Radiant Typhoon Manifestation", "Radiant Typhoon Vision", "Radiant Typhoon Ascendance", "Terraforming"],
    setBackrow: ["Radiant Typhoon Mandate", "Rivalry of Warlords", "Gozen Match", "Infinite Impermanence"],
    extraBosses: ["Radiant Typhoon Varuroon, the Marine Eidolon", "Promethean Princess, Bestower of Flames", "S:P Little Knight", "Worldsea Dragon Zealantis"],
    responders: [],
  }),
  p({
    premadeId: "tcg-elfnote",
    name: "Elfnote",
    role: "midrange",
    playstyle: "Fairy narrative midrange. NS Lucina/Tinia, resolve Welcome Home, Synchro June Pride/Seraphim.",
    comboOutline: ["NS Elfnote name", "Welcome Home / Plea for Help", "Synchro Pride/Seraphim", "Generic links"],
    endBoard: ["Elfnote June Pride", "Elfnote Seraphim Strelitzia", "Chaos Angel"],
    normalSummon: ["Elfnote Lucina", "Elfnote Tinia", "Elfnote Regina", "Elfnote Fortuna", "Elfnote Power Patron"],
    engineSpells: ["Elfnotes: Welcome Home", "Elfnotes: A Plea for Help"],
    setBackrow: ["Elfnotes: Aristeia of Trust", "Elfnotes: Quatrain of Succession", "Elfnotes: Rhapsodia of Madness", "Dimensional Barrier", "Infinite Impermanence"],
    extraBosses: ["Elfnote June Pride", "Elfnote Seraphim Strelitzia", "Chaos Angel", "Herald of the Arc Light", "S:P Little Knight"],
    responders: [],
  }),
  p({
    premadeId: "tcg-sky-striker",
    name: "Sky Striker",
    role: "control",
    playstyle: "Control Link. Engage into Kagari/Shizuku, Widow Anchor, grind with Multirole. Rarely NS anything but Raye.",
    comboOutline: ["Engage / Raye", "Kagari recycle Engage", "Shizuku search", "Widow Anchor + Hornet Drones", "Accesscode only to close"],
    endBoard: ["Sky Striker Ace - Kagari", "Sky Striker Ace - Shizuku", "Sky Striker Ace - Zeke"],
    normalSummon: ["Sky Striker Ace - Raye", "Sky Striker Ace - Roze"],
    engineSpells: ["Sky Striker Mobilize - Engage!", "Sky Striker Maneuver - Afterburners!", "Sky Striker Maneuver - Jamming Waves!", "Sky Striker Mecha - Hornet Drones", "Sky Striker Mecha - Widow Anchor", "Sky Striker Mecha - Shark Cannon", "Sky Striker Mecha Modules - Multirole", "Sky Striker Special Maneuver - Lemnisgate!", "Upstart Goblin", "Pot of Desires", "Pot of Prosperity", "Reinforcement of the Army"],
    setBackrow: ["There Can Be Only One", "Dimensional Barrier", "Infinite Impermanence"],
    extraBosses: ["Sky Striker Ace - Kagari", "Sky Striker Ace - Shizuku", "Sky Striker Ace - Hayate", "Sky Striker Ace - Zeke", "Sky Striker Ace - Azalea", "Heretical Phobos Covos", "Accesscode Talker"],
    responders: [],
    extraAggression: 0.7,
    minAttackers: 1,
  }),
  p({
    premadeId: "tcg-blitzclique",
    name: "Blitzclique",
    role: "aggro",
    playstyle: "Chaos Origins climb with Thunder Dragon fusions. NS Emi/Grain/Surge, fuse Colossus/Titan.",
    comboOutline: ["NS Blitzclique name", "Resolve Steppleader/Breakaway", "Fuse Thunder Dragon Colossus", "Generic links"],
    endBoard: ["Thunder Dragon Colossus", "Thunder Dragon Titan", "S:P Little Knight"],
    normalSummon: ["Emi Blitzclique", "Grain Blitzclique", "Surge Blitzclique", "Whisker Blitzclique", "Crackle Blitzclique", "Thunder Dragondark", "Thunder Dragonhawk", "Thunder Dragonroar"],
    engineSpells: ["Blitzclique - Steppleader", "Blitzclique - Breakaway"],
    setBackrow: ["Blitzclique Alternator", "Blitzclique Return Stroke", "Infinite Impermanence"],
    extraBosses: ["Thunder Dragon Colossus", "Thunder Dragon Titan", "S:P Little Knight", "Accesscode Talker"],
    responders: [],
  }),
  p({
    premadeId: "tcg-dark-magician-azamina",
    name: "Dark Magician Azamina",
    role: "midrange",
    playstyle:
      "DM + Primite + Azamina/Diabellstar. Souls/Illusion into DM, WANTED/Diabellstar into Azamina fusions, Primite Lode/Beryl into Berzelius/Dragoon lines.",
    comboOutline: [
      "Magicians' Souls or Illusion of Chaos to access Dark Magician.",
      "WANTED / Diabellstar into The Hallowed Azamina.",
      "Primite Lordly Lode + Ether Beryl for Primite Fusion / Berzelius.",
      "Gaze of Timaeus / Soul Servant / Circle to climb Dragoon or Timaeus.",
      "Set Eternal Soul or keep Salvation depending on turn order.",
    ],
    endBoard: ["Red-Eyes Dark Dragoon", "Azamina Ilia Silvia", "Selene, Queen of the Master Magicians", "S:P Little Knight"],
    normalSummon: ["Magician's Rod", "Primite Dragon Ether Beryl", "Diabellstar the Black Witch", "Magicians' Souls"],
    engineSpells: [
      "WANTED: Seeker of Sinful Spoils",
      "Primite Lordly Lode",
      "The Hallowed Azamina",
      "Soul Servant",
      "Dark Magical Circle",
      "The Gaze of Timaeus",
      "Primite Fusion",
      "Secrets of Dark Magic",
      "Magician's Salvation",
      "Deception of the Sinful Spoils",
    ],
    setBackrow: ["Eternal Soul", "Infinite Impermanence", "Primite Drillbeam", "Primite Roar"],
    extraBosses: [
      "Red-Eyes Dark Dragoon",
      "Dark Magician of Destruction",
      "Timaeus the United Magical Dragon",
      "Azamina Ilia Silvia",
      "Azamina Mu Rcielago",
      "Primite Dragon Nether Berzelius",
      "Selene, Queen of the Master Magicians",
      "S:P Little Knight",
      "Accesscode Talker",
    ],
    responders: ["Ghost Belle & Haunted Mansion"],
    extraAggression: 0.8,
  }),
  p({
    premadeId: "md-vs-k9",
    name: "Vanquish Soul K9",
    role: "midrange",
    playstyle: "Attribute reveal midrange + K9 Xyz. NS Razen/Izuna, Stake your Soul, overlay Ripper/Hound.",
    comboOutline: ["NS Razen or Izuna", "Stake your Soul / Case for K9", "Xyz Ripper/Werewolf", "Rock of the Vanquisher"],
    endBoard: ['K9-17 "Ripper"', "Rock of the Vanquisher", "Divine Arsenal AA-ZEUS - Sky Thunder"],
    normalSummon: ["Vanquish Soul Razen", 'K9-17 Izuna', "Vanquish Soul Heavy Borger", "Vanquish Soul Dr. Mad Love", "K9-ØØ Lupis"],
    engineSpells: ["Stake your Soul!", '"A Case for K9"', "K9-LC Release Restraint"],
    setBackrow: ["Vanquish Soul Dust Devil", "Infinite Impermanence"],
    extraBosses: ['K9-17 "Ripper"', 'K9-ØØ "Hound"', 'K9-X "Werewolf"', "Rock of the Vanquisher", "Divine Arsenal AA-ZEUS - Sky Thunder", "S:P Little Knight"],
    responders: [],
  }),
  p({
    premadeId: "md-yummy",
    name: "Yummy",
    role: "combo",
    playstyle: "Synchro candy engine. NS Cupsy/Cooky/Lollipo, Synchro ★Yummy Way, Link Snatchy.",
    comboOutline: ["NS ☆Yummy name", "Field Yummyusment", "Synchro Way monsters", "Link Snatchy + Herald"],
    endBoard: ["Cupsy★Yummy Way", "Yummy★Snatchy", "Herald of the Arc Light"],
    normalSummon: ["Cupsy☆Yummy", "Cooky☆Yummy", "Lollipo☆Yummy", "Marshmao☆Yummy"],
    engineSpells: ["Yummyusment☆Mignon", "Yummyusment★Acroquey", "Yum☆Yum☆Yummys", "Yummy☆Surprise"],
    setBackrow: ["Assist★Yummy!", "Yummy★Redemption", "Infinite Impermanence"],
    extraBosses: ["Cupsy★Yummy Way", "Cooky★Yummy Way", "Lollipo★Yummy Way", "Yummy★Snatchy", "Herald of the Arc Light", "S:P Little Knight"],
    responders: [],
    extraAggression: 0.88,
  }),
  p({
    premadeId: "md-ryzeal",
    name: "Ryzeal",
    role: "combo",
    playstyle: "Rank 4 engine. NS Ice/Sword, Plugin/Cross, overlay Detonator + Duo Drive into ZEUS.",
    comboOutline: ["NS Ice or Sword Ryzeal", "Bonfire / Seventh Tachyon", "Xyz Detonator / Duo Drive", "ZEUS / TY-PHON"],
    endBoard: ["Ryzeal Detonator", "Ryzeal Duo Drive", "Divine Arsenal AA-ZEUS - Sky Thunder"],
    normalSummon: ["Ice Ryzeal", "Sword Ryzeal", "Node Ryzeal", "Ext Ryzeal", "Palm Ryzeal", "Star Ryzeal"],
    engineSpells: ["Ryzeal Cross", "Ryzeal Plugin", "Seventh Tachyon", "Bonfire", "Pot of Prosperity"],
    setBackrow: ["Ryzeal Plasma Hole", "Ryzeal Mass Driver", "Infinite Impermanence"],
    extraBosses: ["Ryzeal Detonator", "Ryzeal Duo Drive", "Eclipse Twins", "Divine Arsenal AA-ZEUS - Sky Thunder", "Number 41: Bagooska the Terribly Tired Tapir", "S:P Little Knight"],
    responders: [],
    extraAggression: 0.9,
  }),
  p({
    premadeId: "md-snake-eye",
    name: "Snake-Eye",
    role: "combo",
    playstyle: "FIRE place-as-Continuous combo. NS Ash/Poplar, Bonfire/OSS, climb Flamberge + Princess + I:P/S:P.",
    comboOutline: ["NS Snake-Eye Ash or Poplar", "Bonfire / Original Sinful Spoils", "Place and climb to Flamberge", "Princess + I:P into S:P"],
    endBoard: ["Snake-Eyes Flamberge Dragon", "Promethean Princess, Bestower of Flames", "I:P Masquerena", "S:P Little Knight"],
    normalSummon: ["Snake-Eye Ash", "Snake-Eyes Poplar", "Snake-Eye Oak", "Snake-Eye Birch", "Diabellstar the Black Witch"],
    engineSpells: ["Bonfire", "Original Sinful Spoils - Snake-Eye", "WANTED: Seeker of Sinful Spoils", "Divine Temple of the Snake-Eye", "One for One"],
    setBackrow: ["Startling Stare of the Snake-Eyes", "Infinite Impermanence"],
    extraBosses: ["Promethean Princess, Bestower of Flames", "I:P Masquerena", "S:P Little Knight", "Apollousa, Bow of the Goddess", "Accesscode Talker", "Fiendsmith's Requiem"],
    responders: [],
    extraAggression: 0.9,
  }),
  p({
    premadeId: "md-labrynth",
    name: "Labrynth",
    role: "control",
    playstyle: "Trap control. Set Welcome/Big Welcome, NS Lovely/Arianna only if needed, flood with Barrier/Skill Drain, Extravagance early.",
    comboOutline: ["Pot of Extravagance if needed", "Set Welcome Labrynth / Big Welcome", "NS Arianna or Lovely if no traps", "Floodgates + Rollback"],
    endBoard: ["Lovely Labrynth of the Silver Castle", "Welcome Labrynth", "Skill Drain"],
    normalSummon: ["Arianna the Labrynth Servant", "Lady Labrynth of the Silver Castle", "Lovely Labrynth of the Silver Castle", "Arias the Labrynth Butler", "Labrynth Chandraglier", "Labrynth Stovie Torbie", "Labrynth Cooclock"],
    engineSpells: ["Pot of Extravagance", "Labrynth Labyrinth"],
    setBackrow: ["Big Welcome Labrynth", "Welcome Labrynth", "Infinite Impermanence", "Skill Drain", "Dimensional Barrier", "Different Dimension Ground", "Trap Trick", "Dogmatika Punishment", "Transaction Rollback"],
    extraBosses: ["Chaos Angel", "Garura, Wings of Resonant Life", "Elder Entity N'tss", "S:P Little Knight"],
    responders: [],
    extraAggression: 0.35,
    minAttackers: 2,
  }),
  p({
    premadeId: "md-crystron",
    name: "Crystron",
    role: "combo",
    playstyle: "Synchro Machine toolbox. NS Sulfefnir/Tristaros/Smiger, Inclusion, climb Quandax → Quariongandrax / Phoenix.",
    comboOutline: ["NS Sulfefnir or Tristaros", "Inclusion mill/search", "Synchro Quandax/Eleskeletus", "Quariongandrax or Phoenix"],
    endBoard: ["Crystron Quariongandrax", "Crystron Eleskeletus", "F.A. Dawn Dragster"],
    normalSummon: ["Crystron Sulfefnir", "Crystron Tristaros", "Crystron Smiger", "Crystron Sulfador", "Crystron Citree"],
    engineSpells: ["Crystron Inclusion", "Foolish Burial", "Tuning"],
    setBackrow: ["Crystron Cluster", "Crystron Impact", "Crystron Entry", "Infinite Impermanence"],
    extraBosses: ["Crystron Quariongandrax", "Crystron Phoenix", "Crystron Eleskeletus", "Crystron Quandax", "Crystron Ametrix", "F.A. Dawn Dragster", "S:P Little Knight"],
    responders: [],
    extraAggression: 0.85,
  }),
];

const byId = new Map(PROFILES.map((p) => [p.premadeId, p]));

export function botProfileFor(premadeId: string | undefined | null): BotProfile {
  if (premadeId && byId.has(premadeId)) return byId.get(premadeId)!;
  return p({
    premadeId: premadeId ?? "generic",
    name: "Lab Bot",
    role: "midrange",
    playstyle: "Generic midrange: summon, set backrow, climb Extra if able, respect handtraps.",
    comboOutline: ["Normal Summon a monster", "Set traps", "Extra Deck if board exists"],
    endBoard: ["S:P Little Knight"],
    normalSummon: [],
    engineSpells: [],
    setBackrow: ["Infinite Impermanence"],
    extraBosses: ["S:P Little Knight", "I:P Masquerena", "Accesscode Talker"],
    responders: [],
  });
}

export function allBotProfiles() {
  return PROFILES;
}
