export type StapleRole = "handtrap" | "board-breaker" | "floodgate" | "tech" | "starter-generic";

export const STAPLES: Record<string, StapleRole[]> = {
  "ash blossom & joyous spring": ["handtrap"],
  "ghost belle & haunted mansion": ["handtrap"],
  "ghost ogre & snow rabbit": ["handtrap"],
  "ghost mourner & moonlit chill": ["handtrap"],
  "ghost sister & spooky dogwood": ["handtrap"],
  "effect veiler": ["handtrap"],
  "infinite impermanence": ["handtrap"],
  "droll & lock bird": ["handtrap"],
  "nibiru, the primal being": ["handtrap"],
  "dimension shifter": ["handtrap"],
  "mulcharmy fuwalos": ["handtrap"],
  "mulcharmy purulia": ["handtrap"],
  "mulcharmy meowls": ["handtrap"],
  "maxx \"c\"": ["handtrap"],
  "called by the grave": ["tech"],
  "crossout designator": ["tech"],
  "solemn judgment": ["tech"],
  "solemn strike": ["tech"],
  "solemn warning": ["tech"],
  "lightning storm": ["board-breaker"],
  "harpie's feather duster": ["board-breaker"],
  "raigeki": ["board-breaker"],
  "dark hole": ["board-breaker"],
  "evenly matched": ["board-breaker"],
  "dark ruler no more": ["board-breaker"],
  "forbidden droplet": ["board-breaker"],
  "kaiju": ["board-breaker"],
  "interrupted kaiju slumber": ["board-breaker"],
  "skill drain": ["floodgate"],
  "gozen match": ["floodgate"],
  "rivalry of warlords": ["floodgate"],
  "there can be only one": ["floodgate"],
  "summon limit": ["floodgate"],
  "anti-spell fragrance": ["floodgate"],
  "dimensional barrier": ["floodgate"],
  "pot of prosperity": ["starter-generic"],
  "pot of extravagance": ["starter-generic"],
  "pot of desires": ["starter-generic"],
  "pot of duality": ["starter-generic"],
  "bonfire": ["starter-generic"],
  "terraforming": ["starter-generic"],
  "reinforcement of the army": ["starter-generic"],
  "foolish burial": ["starter-generic"],
  "monster reborn": ["tech"],
  "one for one": ["starter-generic"],
};

export function stapleRoles(name: string): StapleRole[] {
  return STAPLES[name.toLowerCase()] ?? [];
}
